### ISSUE TITLE
Test Steady Shot With Auto Attack/Auto Shot Toggle

### ISSUE THREAD

**Issue by BradBlondebeard** [watchyoursixx/hunter-wotlk-classic#15]
Old EJ posts say that if you have the auto attack/auto shot toggle off, auto shot will not shoot while you are casting steady, test to see if the toggle makes any difference. This could potentially also affect weaving.

**Comment by watchyoursixx** [comment]
Tested with option on and off, makes no difference at the moment. Waiting to see how it changes when auto can go through casts

**Comment by watchyoursixx** [comment]
after steady shot fix this doesn't change whether it works through steady shot or not
