### ISSUE TITLE
Does the 15% "Quiver" Haste affect all shots with cast time?

### ISSUE THREAD

**Issue by BradBlondebeard** [watchyoursixx/hunter-wotlk-classic#17]
Quivers no longer reduce cast time, the 15% haste is baked in. Does that affect all shots with a cast time (steady, presumably multi, and auto)? Or is it only auto?

**Comment by watchyoursixx** [comment]
Auto shot does not have a cast time, but it does have an unchangeable start time of approx. 0.15 seconds.

Multi's cast of 0.5 is still affected by 15% static haste.
Steady's cast 2.0 is still affected by 15% static haste.
