### ISSUE TITLE
Do Pet Abilities Follow A Priority System

### ISSUE THREAD

**Issue by BradBlondebeard** [watchyoursixx/hunter-wotlk-classic#27]
For example do lower focus cost spells (generally family skills) cast before focus dump skills? Most family skills cost 20 focus while the focus dumps cost 25. With the smoother focus regen naturally 20 focus cost skills would be used first, but what about when there is enough focus to cast either, like what happens after you proc Go For The Throat?

**Comment by watchyoursixx** [comment]
Been a bit, but I tested this a few times with several different pet specials. It appears that it is still "random" in that bite or ravage, or bite or breath could be used, whatever the pet feels like if it has the focus for either spell.
